name: Enables auto-merge on dependency pull requests
"on":
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  enable-automerge:
    if: |
      contains(github.event.pull_request.labels.*.name, 'automatic-merge')
      && (
        contains(github.event.pull_request.labels.*.name, 'minor')
        || contains(github.event.pull_request.labels.*.name, 'patch')
      )
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge
        run: |
          gh pr merge --merge --auto "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}