name: Test Demo 1

on:
  pull_request:
    paths:
      - '/**'
    branches: [ main ]

  workflow_dispatch: {}

jobs:
  test-demo-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '21'
      - run: ./mvn clean test
